on:
    pull_request:
    push:
      branches-ignore:
        - main
jobs:
    cfssl:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - run: docker build -t rasenmaeher_cfssl .
      - run: docker run -d -p 8888:8888 rasenmaeher_cfssl && curl http://localhost:8888
